# Generated by Django 3.1.4 on 2023-08-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_auto_20230813_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='codigo_de_barras',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
