# Generated by Django 4.1.2 on 2023-08-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0004_alter_categoria_id_alter_fornecedor_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_da_compra', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('quantidade_produtos', models.CharField(max_length=150, null=True)),
                ('data_compra', models.DateTimeField(auto_now_add=True)),
                ('produtos', models.ManyToManyField(blank=True, related_name='pedidos', to='produtos.produto')),
            ],
        ),
    ]
