# Generated by Django 4.1.2 on 2023-08-22 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0002_alter_carrinho_produtos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='produtos',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='produtos_nomes',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
