# Generated by Django 4.1.2 on 2023-08-24 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0003_remove_carrinho_produtos_carrinho_produtos_nomes'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='produtos_quantidades',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='produtos_valores',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
